### ISSUE TITLE
missav invalid 다운로드 오류 문의드립니다

### ISSUE THREAD

**Issue by fuworker** [rickmiron/variado#12]
작업정보 내용 함께 첨부합니다

Invalid: [missav] https://missav.com/dm1/cn/video/333796/%E5%A4%95%E6%A8%B9%E8%88%9E%E5%AD%90-minami-nakamoto---sister-kiss-nomo-%E5%AE%B6%E6%94%BF%E5%A9%A6.html

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 3d5480fd17684f3abb2b0f6e37d51733
input: https://missav.com/dm1/cn/video/333796/%E5%A4%95%E6%A8%B9%E8%88%9E%E5%AD%90-minami-nakamoto---sister-kiss-nomo-%E5%AE%B6%E6%94%BF%E5%A9%A6.html
type: missav
single: True
url: https://missav.com/dm1/cn/video/333796/%E5%A4%95%E6%A8%B9%E8%88%9E%E5%AD%90-minami-nakamoto---sister-kiss-nomo-%E5%AE%B6%E6%94%BF%E5%A9%A6.html
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1709661305.7307525 (24-03-05 17:55:05 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.12.30
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Get ofuscado
Get ofuscado
Invalid URL '': No scheme supplied. Perhaps you meant https://?
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "dynamic_module_1", line 133, in read
 File "dynamic_module_1", line 34, in __init__
 File "dynamic_module_1", line 29, in __init__
 File "dynamic_module_1", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 452, in read_html
 File "requests\sessions", line 602, in get
 File "utils", line 996, in request
 File "downloader", line 249, in session_request
 File "requests\sessions", line 575, in request
 File "requests\sessions", line 486, in prepare_request
 File "requests\models", line 368, in prepare
 File "requests\models", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

Invalid: fail=True
EOT: https://missav.com/dm1/cn/video/333796/%E5%A4%95%E6%A8%B9%E8%88%9E%E5%AD%90-minami-nakamoto---sister-kiss-nomo-%E5%AE%B6%E6%94%BF%E5%A9%A6.html  (0.9s)

**Comment by rickmiron** [comment]
이미 수리했어요

**Comment by fuworker** [comment]
감사합니다 해결되었습니다
