### ISSUE TITLE
missav가 다운이 되지 않습니다.

### ISSUE THREAD

**Issue by suzukioha** [rickmiron/variado#17]
4분 58초 뒤 다시 시작: Invalid: [missav] https://missav.com/dm26/en/core-042-uncensored-leak

version: 4.1+ (24-03-02 03:38:42 UTC)
platform / locale: Windows-10-10.0.19043-SP0 / ko_kr
order / group / uid: 0 / False / 0244b087c4fb4c93977201cf7aecb6be
input: https://missav.com/dm26/en/core-042-uncensored-leak
type: missav
single: True
url: https://missav.com/dm26/en/core-042-uncensored-leak
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1710936428.1458821 (24-03-20 12:07:08 UTC) - 7s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2024.03.10
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Get ofuscado
Get ofuscado
403 Client Error: Forbidden for url: https://surrit.com/d09eaea6-f912-4af2-a23b-c1c7f02049c4/480p/video.m3u8
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1397, in start
 File "utils", line 1476, in start_
 File "decorator", line 232, in fun
 File "constants", line 947, in try_
 File "constants", line 916, in try_
 File "dynamic_module_20", line 131, in read
 File "dynamic_module_20", line 34, in __init__
 File "dynamic_module_20", line 29, in __init__
 File "dynamic_module_20", line 25, in <lambda>
 File "decorator", line 232, in fun
 File "constants", line 947, in try_
 File "constants", line 916, in try_
 File "m3u8_tools", line 144, in __init__
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://surrit.com/d09eaea6-f912-4af2-a23b-c1c7f02049c4/480p/video.m3u8

Invalid: fail=True
EOT: https://missav.com/dm26/en/core-042-uncensored-leak  (3.8s)

Get ofuscado
Get ofuscado
403 Client Error: Forbidden for url: https://surrit.com/d09eaea6-f912-4af2-a23b-c1c7f02049c4/playlist.m3u8
stop
Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 531, in open
 File "urllib\request", line 640, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1397, in start
 File "utils", line 1476, in start_
 File "decorator", line 232, in fun
 File "constants", line 947, in try_
 File "constants", line 916, in try_
 File "dynamic_module_21", line 124, in read
 File "dynamic_module_21", line 22, in __init__
 File "decorator", line 232, in fun
 File "constants", line 947, in try_
 File "constants", line 916, in try_
 File "dynamic_module_21", line 94, in ofuscado
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://surrit.com/d09eaea6-f912-4af2-a23b-c1c7f02049c4/playlist.m3u8

Invalid: fail=True
EOT: https://missav.com/dm26/en/core-042-uncensored-leak  (4.5s)

m3u8 클라이언트가 에러뜬다고 뜨는 거 같은데 뭐가 문제인지 모르겠습니다 ㅠㅠ
저는 480p 화질로 받는 것을 선호해서 missav에 480p가 없는 건가 했는데 사이트에는 480p로 정상적으로 재생이 됩니다.

**Comment by rickmiron** [comment]
이미 수리했어요

**Comment by rickmiron** [comment]
업데이트된 py 파일을 다운로드하고 480 버전에 대해 위의 변경 사항을 적용하세요.
YouTube 옵션에서 비디오 품질을 선택 가능하게 만들 수 있지만 더 이상 720을 다운로드할 수 없으며 선택한 품질보다 낮을 뿐입니다.

**Comment by suzukioha** [comment]
감사합니다! 잘 됩니다 ! 
그런데 히토미다운로더의 유튜브 옵션으로 화질을 설정하는 것은 어떻게 하나요?

오래된

un = codigo.find('\n',codigo.rfind('INF:'))+1
새로운

un = codigo.find('\n',codigo.find('INF:',codigo.find('INF:')+1))+1

스크립트를 이렇게 변경해주고 하면 되는건가요?

스크립트를 바꾸기 전에 원본 스크립트로 했을 때는 히토미다운로더 유튜브 설정에서 480P 720P 1080P 화질을 설정해도 적용되지 않았습니다. ( un = codigo.find('\n',codigo.rfind('INF:'))+1  이 스크립트일 때)

스크립트를 바꾸고 나서도 유튜브 설정대로 받아지지 않습니다.
( un = codigo.find('\n',codigo.find('INF:',codigo.find('INF:')+1))+1 이 스크립트로 수정했을 때 )

개인적으로는 히토미다운로더에 있는 유튜브 설정에서 선택한 화질대로 받아지는 게 가장 좋을 것 같다고 생각합니다

**Comment by rickmiron** [comment]
방금 그 기능을 추가했어요

**Comment by suzukioha** [comment]
감사합니다! 직접 해본 결과 잘 됩니다 !

**Comment by RukayyatRadiant170** [comment]
우회주소 남겨드리고 갈께요. 즐감하시고요.

좌표 ☞ http://missav-69.com/19
