### ISSUE TITLE
플러그인 추가 후 동영상 다운로드시 invalid 오류 발생에 대한 문의입니다

### ISSUE THREAD

**Issue by fuworker** [rickmiron/variado#18]
다운로드 받은 av19.py파일 플러그인 추가 후 다운로드 진행하였는데 갑자기 invalid 오류가 발생합니다
확인 부탁드리겠습니다 하단에 작업정보 첨부하였습니다

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Invalid: [av19] https://av19.gg/bbs/board.php?bo_table=bj&wr_id=5009

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / a6f0be7efdf24f19b248eb29870ba015
input: https://av19.gg/bbs/board.php?bo_table=bj&wr_id=5009
type: av19
single: True
url: https://av19.gg/bbs/board.php?bo_table=bj&wr_id=5009
dir:
zip:
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711272152.545231 (24-03-24 09:22:32 UTC) - 196s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Invalid URL '': No scheme supplied. Perhaps you meant https://?
stop
Traceback (most recent call last):
File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1395, in start
File "utils", line 1474, in start_
File "dynamic_module_1", line 31, in read
File "dynamic_module_1", line 29, in read
File "dynamic_module_1", line 27, in
File "decorator", line 232, in fun
File "constants", line 942, in try_
File "constants", line 911, in try_
File "m3u8_tools", line 144, in init
File "downloader", line 452, in read_html
File "requests\sessions", line 602, in get
File "utils", line 996, in request
File "downloader", line 249, in session_request
File "requests\sessions", line 575, in request
File "requests\sessions", line 486, in prepare_request
File "requests\models", line 368, in prepare
File "requests\models", line 439, in prepare_url
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

Invalid: fail=True
EOT: https://av19.gg/bbs/board.php?bo_table=bj&wr_id=5009 (0.6s)

**Comment by rickmiron** [comment]
이미 수리했어요

**Comment by fuworker** [comment]
해결되었습니다 감사합니다!
