### ISSUE TITLE
sogirl 사용시 멈춤

### ISSUE THREAD

**Issue by fatuming** [rickmiron/variado#22]
Joining parts...ABF-092-미노시마 메구리 HD

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / ba3e33d4c3df4ed18191caaf54b8e8ca
input: https://kr64.sogirl.so/abf-092-%EB%AF%B8%EB%85%B8%EC%8B%9C%EB%A7%88-%EB%A9%94%EA%B5%AC%EB%A6%AC-hd/
type: sogirl
single: False
url: https://kr64.sogirl.so/abf-092-%EB%AF%B8%EB%85%B8%EC%8B%9C%EB%A7%88-%EB%A9%94%EA%B5%AC%EB%A6%AC-hd/
dir: hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1712498110.9704323 (24-04-07 13:55:10 UTC) - 541s elapsed
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: None None
pinned: False
extras: {}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD\0
[0002] hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD\1
[0003] hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD\2
[0004] hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD\3
[0005] hitomi_downloaded_sogirl\ABF-092-미노시마 메구리 HD\4
[2275] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2274.ts?v=758&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2274
[2276] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2275.ts?v=758&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2275
[2277] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2276.ts?v=758&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2276
[2278] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2277.ts?v=759&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2277
[2279] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2278.ts?v=759&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2278
[2280] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2279.ts?v=759&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2279
[2281] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2280.ts?v=760&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2280
[2282] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2281.ts?v=760&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2281
[2283] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2282.ts?v=760&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2282
[2284] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2283.ts?v=761&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2283
[2285] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2284.ts?v=761&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2284
[2286] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2285.ts?v=761&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2285
[2287] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2286.ts?v=762&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2286
[2288] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2287.ts?v=762&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2287
[2289] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2288.ts?v=762&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2288
[2290] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2289.ts?v=763&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2289
[2291] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2290.ts?v=763&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2290
[2292] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2291.ts?v=763&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2291
[2293] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2292.ts?v=764&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2292
[2294] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2293.ts?v=764&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2293
[2295] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2294.ts?v=764&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2294
[2296] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2295.ts?v=765&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2295
[2297] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2296.ts?v=765&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2296
[2298] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2297.ts?v=765&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2297
[2299] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2298.ts?v=766&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2298
[2300] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2299.ts?v=766&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2299
[2301] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2300.ts?v=766&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2300
[2302] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2301.ts?v=767&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2301
[2303] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2302.ts?v=767&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2302
[2304] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2303.ts?v=767&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2303
[2305] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2304.ts?v=768&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2304
[2306] LazyUrl(https://vz-b5c3d97e-23f.b-cdn.net/0a351930-8317-4ffe-bd6a-3f697392899c/720p/video2305.ts?v=768&resolution=720p&server=806&contextId=7d4b2ad1-0bcd-4f40-ad23-981000712311)    --->    【local_lazy】 2305

[Messages]
stop
Traceback (most recent call last):
 File "utils", line 1667, in finish
 File "dynamic_module_1", line 71, in post_processing
 File "ffmpeg", line 173, in run
 File "decorator", line 232, in fun
 File "locker", line 64, in _wrapper
 File "ffmpeg", line 142, in load
Exception: Failed to download

EOT: https://kr64.sogirl.so/abf-092-%EB%AF%B8%EB%85%B8%EC%8B%9C%EB%A7%88-%EB%A9%94%EA%B5%AC%EB%A6%AC-hd/  (376.3s)

파타를 합치다가 멈추는것 같은데 다른 이유가 있을까요 ?>

**Comment by rickmiron** [comment]
변경사항을 적용했습니다. 시도해 보세요.

**Comment by fatuming** [comment]
> 변경사항을 적용했습니다. 시도해 보세요.

감사합니다.
