### ISSUE TITLE
케모노 플러그인이 두 개인데 무슨 차이가 있나요??

### ISSUE THREAD

**Issue by juddem002** [rickmiron/variado#36]
그냥 케모노랑 퀄리티 제로 케모노가 있더라구요.

혹시 무슨 차이가 있는지 여쭤도 될까요??

**Comment by juddem002** [comment]
아 그리고 히토미 다운로더에서 설정-플러그인-+로 추가하면 된다고 밑에 글에 작성해주셨는데, 
올바른 형식의 스크립트가 아니라고 뜨면  제가 뭔가를 잘못한걸까요??

**Comment by rickmiron** [comment]
이 버전이 더 좋습니다. Qualiazero 는 사용자 이름이고 해당 사용자가 몇 가지 개인적인 변경 사항을 요청했기 때문에 파일 이름을 지정했는데, 이것이 가장 업데이트된 파일이 되었습니다

오류 메시지 보여 줘

**Comment by juddem002** [comment]
그냥 +누르고 파일 선택 후 플러그인 추가하는게 맞나요??
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 5715, in exec_script
  File "dynamic_module_5", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

이렇게 나옵니다. 어떻게 사용하는지 잘 모르겠어요.

**Comment by rickmiron** [comment]
다른 플러그인을 사용해 보셨나요?
