### ISSUE TITLE
Civitai 다운이 안 되네요

### ISSUE THREAD

**Issue by Behemoth-98** [rickmiron/variado#65]
Invalid: [civitai] https://civitai.com/user/ksjk

version: 4.1 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 15 / False / a00e39e6050f438c9a1520cb07645abc
input: https://civitai.com/user/ksjk
type: civitai
single: False
url: https://civitai.com/user/ksjk
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1730897128.2934458 (24-11-06 12:45:28 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 31, in geto
IndexError: list index out of range

Invalid: fail=True
EOT: https://civitai.com/user/ksjk  (1.0s)

list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 31, in geto
IndexError: list index out of range

Invalid: fail=True
EOT: https://civitai.com/user/ksjk  (0.6s)

list index out of range
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Civitai", line 24, in read
 File "Civitai", line 31, in geto
IndexError: list index out of range

Invalid: fail=True
EOT: https://civitai.com/user/ksjk  (1.7s)

어떤 이유인지 알 수 있을까요?

**Comment by rickmiron** [comment]
모델의 URL을 다운로드하기 위해 만들었습니다 :
https://civitai.com/models/456882/styles-or-pony-and-animagine
쿠키를 로드해야 합니다.

**Comment by Behemoth-98** [comment]
> 모델의 URL을 다운로드하기 위해 만들었습니다 : https://civitai.com/models/456882/styles-or-pony-and-animagine 쿠키를 로드해야 합니다.

아..모델은 다운받기 위한 거군요...
혹시 작가 갤러리 받을 수 있는 방법은 없을까요?

**Comment by rickmiron** [comment]
I already updated it, try it

**Comment by Behemoth-98** [comment]
> I already updated it, try it

thank you very much!!!
