### ISSUE TITLE
https://missav.com 작동이 안되네요

### ISSUE THREAD

**Issue by OO157** [rickmiron/variado#66]
Invalid: [missav] https://missav.com/dm14/ko/fc2-ppv-3818246

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / a4ece55a5bcb4f1c9ded922d582008ef
input: https://missav.com/dm14/ko/fc2-ppv-3818246
type: missav
single: True
url: https://missav.com/dm14/ko/fc2-ppv-3818246
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1731028086.1585023 (24-11-08 01:08:06 UTC) - 4s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
Get ofuscado
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1421, in connect
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='missav.com', port=443): Max retries exceeded with url: /dm14/ko/fc2-ppv-3818246 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "dynamic_module_24", line 72, in ofuscado
 File "downloader", line 457, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='missav.com', port=443): Max retries exceeded with url: /dm14/ko/fc2-ppv-3818246 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

Get ofuscado
Traceback (most recent call last):
 File "urllib\request", line 1354, in do_open
 File "http\client", line 1252, in request
 File "http\client", line 1298, in _send_request
 File "http\client", line 1247, in endheaders
 File "http\client", line 1007, in _send_output
 File "http\client", line 947, in send
 File "http\client", line 1421, in connect
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "downloader", line 431, in read_html
 File "urllib\request", line 525, in open
 File "urllib\request", line 542, in _open
 File "urllib\request", line 502, in _call_chain
 File "urllib\request", line 1397, in https_open
 File "urllib\request", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "urllib3\connectionpool", line 670, in urlopen
 File "urllib3\connectionpool", line 381, in _make_request
 File "urllib3\connectionpool", line 978, in _validate_conn
 File "urllib3\connection", line 362, in connect
 File "urllib3\util\ssl_", line 386, in ssl_wrap_socket
 File "ssl", line 500, in wrap_socket
 File "ssl", line 1040, in _create
 File "decorator", line 232, in fun
 File "locker", line 123, in _wrapper
 File "locker", line 56, in exec
 File "locker", line 37, in run
 File "locker", line 123, in <lambda>
 File "downloader", line 102, in do_handshake
 File "ssl", line 1309, in do_handshake
ssl.SSLError: [SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "requests\adapters", line 486, in send
 File "urllib3\connectionpool", line 726, in urlopen
 File "urllib3\util\retry", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='missav.com', port=443): Max retries exceeded with url: /dm14/ko/fc2-ppv-3818246 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "dynamic_module_24", line 72, in ofuscado
 File "downloader", line 457, in read_html
 File "requests\sessions", line 602, in get
 File "downloader", line 249, in session_request
 File "requests\sessions", line 589, in request
 File "requests\sessions", line 703, in send
 File "requests\adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='missav.com', port=443): Max retries exceeded with url: /dm14/ko/fc2-ppv-3818246 (Caused by SSLError(SSLError(1, '[SSL: INVALID_SESSION_ID] invalid session id (_ssl.c:1131)')))

local variable 'soup' referenced before assignment
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "dynamic_module_24", line 136, in read
 File "dynamic_module_24", line 21, in __init__
 File "dynamic_module_24", line 75, in ofuscado
UnboundLocalError: local variable 'soup' referenced before assignment

Invalid: fail=True
quality: 100%
EOT: https://missav.com/dm14/ko/fc2-ppv-3818246  (1.0s)

**Comment by OO157** [comment]
작동 되네요
