### ISSUE TITLE
https://hentai.tv/ 작동이 안되네요

### ISSUE THREAD

**Issue by OO157** [rickmiron/variado#71]
Invalid: [hentai.tv] https://hentai.tv/hentai/yoasobi-gurashi-episode-2/

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / ko_kr
order / group / uid: 0 / False / f72b8409acc94a869cd6aeaf776faace
input: https://hentai.tv/hentai/yoasobi-gurashi-episode-2/
type: hentai.tv
single: True
url: https://hentai.tv/hentai/yoasobi-gurashi-episode-2/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1732111146.409036 (24-11-20 13:59:06 UTC) - 86s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
525 Server Error: <none> for url: https://hentai.tv/hentai/yoasobi-gurashi-episode-2/
stop
Traceback (most recent call last):
 File "downloader", line 413, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "dynamic_module_21", line 21, in read
 File "decorator", line 232, in fun
 File "constants", line 942, in try_
 File "constants", line 911, in try_
 File "dynamic_module_21", line 31, in get_video
 File "downloader", line 357, in read_soup
 File "downloader", line 459, in read_html
 File "requests\models", line 1021, in raise_for_status
requests.exceptions.HTTPError: 525 Server Error: <none> for url: https://hentai.tv/hentai/yoasobi-gurashi-episode-2/

Invalid: fail=True
quality: 100%
EOT: https://hentai.tv/hentai/yoasobi-gurashi-episode-2/  (1.4s)

**Comment by scoin1314** [comment]
Google Chrome의 Getvid 동영상 다운로더
