### ISSUE TITLE
coomer 다운로드 불가

### ISSUE THREAD

**Issue by fuzzypurge** [rickmiron/variado#73]
Invalid: [coomer.su] https://coomer.su/onlyfans/user/cuiogeo/post/1388194795

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 8c3e8ee6a55b46d0a5d72bc70bc9c641
input: https://coomer.su/onlyfans/user/cuiogeo/post/1388194795
type: coomer.su
single: False
url: https://coomer.su/onlyfans/user/cuiogeo/post/1388194795
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1732692289.6772308 (24-11-27 07:24:49 UTC) - 10s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: False
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Coomer.Su", line 20, in read
 File "Coomer.Su", line 59, in read_post
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://coomer.su/onlyfans/user/cuiogeo/post/1388194795  (0.7s)

어제 낮까진 괜찮았었는데 저녁부터 invalid 오류가 터집니다.
어느 포스트를 받든 똑같은 문제가 발생합니다.
플러그인도 다시 로드해보고 dns나 vpn도 건드려봤는데 그대로네요.

**Comment by wwkedesde** [comment]
저도 같은 문제가 발생하네요
