### ISSUE TITLE
kemono.su is not working.

### ISSUE THREAD

**Issue by hwakwave** [rickmiron/variado#74]
Invalid: [kemono.party] https://kemono.su/patreon/user/27284461

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 14ba692e3e524b24867aeed6e2dfdfc2
input: https://kemono.su/patreon/user/27284461
type: kemono.party
single: True
url: https://kemono.su/patreon/user/27284461
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1733018653.2792659 (24-12-01 02:04:13 UTC) - 5s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 4320
goodbyedpi: True
ytdl: yt_dlp 2024.10.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su", line 24, in read
 File "Kemono.Su", line 36, in rid_user
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kemono.su/patreon/user/27284461  (0.7s)

===================================================
Thank you for your work and I would appreciate it if you could fix it.

**Comment by hangugin1651** [comment]
I have the same problem and I tried to fix it... but I failed. I hope someone can fix it

**Comment by micomet35** [comment]
Here's same problem too...Is there an expert of it?
