### ISSUE TITLE
Kemono download plugin always identifies more images than the original submission and fails to complete the download task

### ISSUE THREAD

**Issue by Qualiazero** [rickmiron/variado#8]
Hello, I've noticed that the Kemono download plugin always identifies more images than the original submission and fails to complete the download task.

Thank you very much for your development work! As mentioned in the title, I cannot complete other tasks because the download task cannot be finished.

Additionally, I am unable to customize the folder name for each post through option-preference-folder format. I need to place the post number at the beginning. Do you have any solutions for this issue?

안녕하세요, Kemono 다운로드 플러그인을 사용 중인데, 항상 원본 게시물보다 더 많은 이미지를 식별하며 다운로드 작업을 완료할 수 없는 문제가 있습니다.

개발 작업에 대해 정말 감사합니다! 제목에서 언급한대로, 다운로드 작업이 완료되지 않아 다른 작업을 수행할 수 없습니다.

또한, option-preference-folder format을 통해 각 게시물의 폴더 이름을 사용자 정의할 수 없습니다. 게시물 번호를 맨 앞에 두고 싶은데, 이 문제에 대한 해결책이 있을까요?

**Comment by Qualiazero** [comment]
![image](https://github.com/rickmiron/variado/assets/15713953/35cd784b-82f0-457d-b0c2-e16cfb9de61a)

**Comment by rickmiron** [comment]
I made changes, try it

**Comment by xxkzn** [comment]
I found [kemonosu_downloader Qualiazero.py](https://github.com/rickmiron/variado/blob/main/kemonosu_downloader%20Qualiazero.py) can‘t download some posts。like this ：https://kemono.su/gumroad/user/6537248298264 and https://kemono.su/patreon/user/7207629    Mainly appears in patreon and gumroad。
the plugin also can‘t download txt file。

**Comment by rickmiron** [comment]
In the "content" sector it does not capture the links, only images, since in that sector they place the links to external Kemono pages that contain the file, so it would be necessary each time to identify what type of page it is or even just one page empty
What I can do is put all the links I find in "content" in a file.txt, and then manually download them

**Comment by Qualiazero** [comment]
> In the "content" sector it does not capture the links, only images, since in that sector they place the links to external Kemono pages that contain the file, so it would be necessary each time to identify what type of page it is or even just one page empty What I can do is put all the links I find in "content" in a file.txt, and then manually download them


Hello rickmiron! 
Would it be possible for you to put all the content found in the "content" sector, not just the links, into a txt file? 
Sometimes, besides the download links, the author also writes some other valuable content here, and I really hope you can consider this change!

**Comment by rickmiron** [comment]
New features were added:
https://github.com/rickmiron/variado/blob/main/kemonosu_downloader%20Qualiazero.py

**Comment by Qualiazero** [comment]
> New features were added: https://github.com/rickmiron/variado/blob/main/kemonosu_downloader%20Qualiazero.py

Thank you so much rickmiron, this has helped me a lot. Do you have a sponsorship program? I would like to appreciate for your help!

**Comment by Qualiazero** [comment]
> In the "content" sector it does not capture the links, only images, since in that sector they place the links to external Kemono pages that contain the file, so it would be necessary each time to identify what type of page it is or even just one page empty What I can do is put all the links I find in "content" in a file.txt, and then manually download them

Hello, rickmiron! 
It seems that due to the recent update of the Kemono website, the plugin you previously modified is no longer able to identify the image elements on each page of Kemono. The specific error information is as follows. I hope you can take a look! 
Thank you so much!
`
Invalid: [kemono.party] https://kemono.su/fanbox/user/1878082

version: 4.2+ (24-12-13 11:59:12 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / zh_cn
order / group / uid: 0 / False / 6f011c6b2448411c8a8a52aa3de83dc8
input: https://kemono.su/fanbox/user/1878082
type: kemono.party
single: True
url: https://kemono.su/fanbox/user/1878082
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1735191419.842087 (24-12-26 05:36:59 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1403, in start
 File "utils", line 1493, in start_
 File "Kemono.Su", line 24, in read
 File "Kemono.Su", line 36, in rid_user
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://kemono.su/fanbox/user/1878082  (0.4s)
`
